# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mx_platform_python.api.notifications_api import NotificationsApi  # noqa: E501


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_notification(self) -> None:
        """Test case for create_notification

        Create a notification  # noqa: E501
        """
        pass

    def test_list_notifications(self) -> None:
        """Test case for list_notifications

        List notifications  # noqa: E501
        """
        pass

    def test_read_notifications(self) -> None:
        """Test case for read_notifications

        Read notifications  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
