# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.repeating_transactions_response_body import RepeatingTransactionsResponseBody  # noqa: E501

class TestRepeatingTransactionsResponseBody(unittest.TestCase):
    """RepeatingTransactionsResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RepeatingTransactionsResponseBody:
        """Test RepeatingTransactionsResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RepeatingTransactionsResponseBody`
        """
        model = RepeatingTransactionsResponseBody()  # noqa: E501
        if include_optional:
            return RepeatingTransactionsResponseBody(
                repeating_transactions = [
                    mx_platform_python.models.repeating_transaction_response.RepeatingTransactionResponse(
                        account_guid = 'ACT-0af29528-bb91-447f-b5de-85c1c42593e5', 
                        amount = 107.4, 
                        description = 'Dominion Energy', 
                        guid = 'RPT-a2264e1a-d2e6-41d9-88d2-2cfdf1143959', 
                        member_guid = 'MBR-78b14c5f-7297-4fb5-a966-65ac45f74d83', 
                        merchant_guid = 'MCH-1b5d7e4d-fa29-95d1-fd0f-540b6f17d986', 
                        last_posted_date = '2024-12-09', 
                        predicted_occurs_on = '2025-01-09', 
                        recurrence_type = 'EVERY_MONTH', 
                        user_guid = '', 
                        repeating_transaction_type = 'BILL', 
                        transaction_type = 'DEBIT', )
                    ]
            )
        else:
            return RepeatingTransactionsResponseBody(
        )
        """

    def testRepeatingTransactionsResponseBody(self):
        """Test RepeatingTransactionsResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
