# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mx_platform_python.api.members_api import MembersApi  # noqa: E501


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_aggregate_member(self) -> None:
        """Test case for aggregate_member

        Aggregate member  # noqa: E501
        """
        pass

    def test_check_balances(self) -> None:
        """Test case for check_balances

        Check balances  # noqa: E501
        """
        pass

    def test_create_member(self) -> None:
        """Test case for create_member

        Create member  # noqa: E501
        """
        pass

    def test_delete_member(self) -> None:
        """Test case for delete_member

        Delete member  # noqa: E501
        """
        pass

    def test_identify_member(self) -> None:
        """Test case for identify_member

        Identify member  # noqa: E501
        """
        pass

    def test_list_member_challenges(self) -> None:
        """Test case for list_member_challenges

        List member challenges  # noqa: E501
        """
        pass

    def test_list_member_credentials(self) -> None:
        """Test case for list_member_credentials

        List member credentials  # noqa: E501
        """
        pass

    def test_list_members(self) -> None:
        """Test case for list_members

        List members  # noqa: E501
        """
        pass

    def test_read_member(self) -> None:
        """Test case for read_member

        Read member  # noqa: E501
        """
        pass

    def test_read_member_status(self) -> None:
        """Test case for read_member_status

        Read member status  # noqa: E501
        """
        pass

    def test_resume_aggregation(self) -> None:
        """Test case for resume_aggregation

        Resume aggregation  # noqa: E501
        """
        pass

    def test_update_member(self) -> None:
        """Test case for update_member

        Update member  # noqa: E501
        """
        pass

    def test_verify_member(self) -> None:
        """Test case for verify_member

        Verify member  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
