# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.token_response_body import TokenResponseBody  # noqa: E501

class TestTokenResponseBody(unittest.TestCase):
    """TokenResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenResponseBody:
        """Test TokenResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenResponseBody`
        """
        model = TokenResponseBody()  # noqa: E501
        if include_optional:
            return TokenResponseBody(
                tokens = [
                    mx_platform_python.models.token_response.TokenResponse(
                        payment_processor_guid = 'PPR-084aa709-8218-4b5a-b3ab-70ffc7483daf', 
                        expires_at = '2023-04-19T15:38:2800:00', 
                        access_token = 'i8FnF...', 
                        active = True, )
                    ]
            )
        else:
            return TokenResponseBody(
        )
        """

    def testTokenResponseBody(self):
        """Test TokenResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
