# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.notification_response_body import NotificationResponseBody  # noqa: E501

class TestNotificationResponseBody(unittest.TestCase):
    """NotificationResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationResponseBody:
        """Test NotificationResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationResponseBody`
        """
        model = NotificationResponseBody()  # noqa: E501
        if include_optional:
            return NotificationResponseBody(
                notification = mx_platform_python.models.notification_response.NotificationResponse(
                    guid = TF-b53294f5-2356-4782-9f81-ae064c42b40a, 
                    content = The content related to the notification., 
                    deep_link_guid = BGT-e386a323-e452-47f2-b2fd-1ac3c18533de, 
                    delivered_at = null, 
                    entity_guid = BGT-e386a323-e452-47f2-b2fd-1ac3c18533de, 
                    has_been_delivered = true, 
                    has_been_viewed = false, 
                    notification_type = 2, 
                    subject = You're projected to spend $1,920.07 more than you've budgeted for Fees & Charges. You've already spent $65.67 of $316.00., 
                    channel = push, )
            )
        else:
            return NotificationResponseBody(
        )
        """

    def testNotificationResponseBody(self):
        """Test NotificationResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
