# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.users_response_body import UsersResponseBody  # noqa: E501

class TestUsersResponseBody(unittest.TestCase):
    """UsersResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersResponseBody:
        """Test UsersResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersResponseBody`
        """
        model = UsersResponseBody()  # noqa: E501
        if include_optional:
            return UsersResponseBody(
                pagination = mx_platform_python.models.pagination_response.PaginationResponse(
                    current_page = 1, 
                    per_page = 25, 
                    total_entries = 1, 
                    total_pages = 1, ),
                users = [
                    mx_platform_python.models.user_response.UserResponse(
                        email = 'email@provider.com', 
                        guid = 'USR-d74cb14f-fd0a-449f-991b-e0362a63d9c6', 
                        id = 'My-Unique-ID', 
                        is_disabled = False, 
                        metadata = '{\"first_name\": \"Steven\", \"last_name\": \"Universe\"}', )
                    ]
            )
        else:
            return UsersResponseBody(
        )
        """

    def testUsersResponseBody(self):
        """Test UsersResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
