# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.category_response import CategoryResponse  # noqa: E501

class TestCategoryResponse(unittest.TestCase):
    """CategoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoryResponse:
        """Test CategoryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoryResponse`
        """
        model = CategoryResponse()  # noqa: E501
        if include_optional:
            return CategoryResponse(
                created_at = '2015-04-13T18:01:23.000Z',
                guid = 'CAT-7829f71c-2e8c-afa5-2f55-fa3634b89874',
                is_default = True,
                is_income = False,
                metadata = 'some metadata',
                name = 'Auto Insurance',
                parent_guid = 'CAT-7829f71c-2e8c-afa5-2f55-fa3634b89874',
                updated_at = '2015-05-13T18:01:23.000Z'
            )
        else:
            return CategoryResponse(
        )
        """

    def testCategoryResponse(self):
        """Test CategoryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
