# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.holding_response import HoldingResponse  # noqa: E501

class TestHoldingResponse(unittest.TestCase):
    """HoldingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HoldingResponse:
        """Test HoldingResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HoldingResponse`
        """
        model = HoldingResponse()  # noqa: E501
        if include_optional:
            return HoldingResponse(
                account_guid = 'ACT-06d7f44b-caae-0f6e-1384-01f52e75dcb1',
                cost_basis = 827.0,
                created_at = '2015-04-13T18:01:23.000Z',
                currency_code = 'USD',
                cusip = '18383M878',
                daily_change = 2.5,
                description = 'Guggenheim Defensive Equity ETF',
                guid = 'HOL-d65683e8-9eab-26bb-bcfd-ced159c9abe2',
                holding_type = 'MONEY_MARKET',
                holding_type_id = 1,
                id = 'ID-123',
                market_value = 989.5,
                member_guid = 'MBR-d65683e8-9eab-26bb-bcfd-ced159c9abe',
                metadata = 'metadata',
                purchase_price = 26.3,
                shares = 6.0,
                symbol = 'DEF',
                updated_at = '2015-04-13T18:01:23.000Z',
                user_guid = 'USR-743e5d7f-1116-28fa-5de1-d3ba02e41d8d'
            )
        else:
            return HoldingResponse(
        )
        """

    def testHoldingResponse(self):
        """Test HoldingResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
