# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.processor_account_number_body_account_numbers_inner import ProcessorAccountNumberBodyAccountNumbersInner  # noqa: E501

class TestProcessorAccountNumberBodyAccountNumbersInner(unittest.TestCase):
    """ProcessorAccountNumberBodyAccountNumbersInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessorAccountNumberBodyAccountNumbersInner:
        """Test ProcessorAccountNumberBodyAccountNumbersInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessorAccountNumberBodyAccountNumbersInner`
        """
        model = ProcessorAccountNumberBodyAccountNumbersInner()  # noqa: E501
        if include_optional:
            return ProcessorAccountNumberBodyAccountNumbersInner(
                account_guid = 'ACT-283132a4-1401-486a-909e-1605f1623d11',
                member_guid = 'MBR-54feffb9-8474-47bd-8442-de003910113a',
                user_guid = 'USR-101ad774-288b-44ed-ad16-da87d522ea20',
                account_number = 6366816006,
                guid = 'ACN-68c0b681-78c2-4731-9b41-d6e8ae2846cf',
                institution_number = None,
                loan_guarantor = None,
                loan_reference_number = None,
                passed_validation = true,
                routing_number = 242564563,
                sequence_number = None,
                transit_number = None
            )
        else:
            return ProcessorAccountNumberBodyAccountNumbersInner(
        )
        """

    def testProcessorAccountNumberBodyAccountNumbersInner(self):
        """Test ProcessorAccountNumberBodyAccountNumbersInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
