# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.tagging_create_request_body import TaggingCreateRequestBody  # noqa: E501

class TestTaggingCreateRequestBody(unittest.TestCase):
    """TaggingCreateRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaggingCreateRequestBody:
        """Test TaggingCreateRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaggingCreateRequestBody`
        """
        model = TaggingCreateRequestBody()  # noqa: E501
        if include_optional:
            return TaggingCreateRequestBody(
                tagging = mx_platform_python.models.tagging_create_request.TaggingCreateRequest(
                    tag_guid = 'TAG-40faf068-abb4-405c-8f6a-e883ed541fff', 
                    transaction_guid = 'TRN-810828b0-5210-4878-9bd3-f4ce514f90c4', )
            )
        else:
            return TaggingCreateRequestBody(
        )
        """

    def testTaggingCreateRequestBody(self):
        """Test TaggingCreateRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
