# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.spending_plan_response import SpendingPlanResponse  # noqa: E501

class TestSpendingPlanResponse(unittest.TestCase):
    """SpendingPlanResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpendingPlanResponse:
        """Test SpendingPlanResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpendingPlanResponse`
        """
        model = SpendingPlanResponse()  # noqa: E501
        if include_optional:
            return SpendingPlanResponse(
                created_at = '2016-10-13T18:08:00+00:00',
                current_iteration_number = 1,
                guid = 'SPL-e5f9a5bd-c5b3-4901-bdc0-62119b9db262',
                updated_at = '2016-10-13T18:09:00+00:00',
                user_guid = 'USR-fa7537f3-48aa-a683-a02a-b18940482f54'
            )
        else:
            return SpendingPlanResponse(
        )
        """

    def testSpendingPlanResponse(self):
        """Test SpendingPlanResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
