# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.challenge_response import ChallengeResponse  # noqa: E501

class TestChallengeResponse(unittest.TestCase):
    """ChallengeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChallengeResponse:
        """Test ChallengeResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChallengeResponse`
        """
        model = ChallengeResponse()  # noqa: E501
        if include_optional:
            return ChallengeResponse(
                field_name = 'Who is this guy?',
                guid = 'CRD-ce76d2e3-86bd-ec4a-ec52-eb53b5194bf5',
                image_data = 'Who is this guy?',
                image_options = [
                    mx_platform_python.models.image_option_response.ImageOptionResponse(
                        data_uri = 'data:image/png;base64,iVBORw0KGgoAAAANSUh ... more image data ...', 
                        label = 'IMAGE_1', 
                        value = 'image_data', )
                    ],
                label = 'Who is this guy?',
                options = [
                    mx_platform_python.models.option_response.OptionResponse(
                        label = 'IMAGE_1', 
                        value = 'image_data', )
                    ],
                type = 'IMAGE_DATA'
            )
        else:
            return ChallengeResponse(
        )
        """

    def testChallengeResponse(self):
        """Test ChallengeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
