# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.connect_widget_response_body import ConnectWidgetResponseBody  # noqa: E501

class TestConnectWidgetResponseBody(unittest.TestCase):
    """ConnectWidgetResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConnectWidgetResponseBody:
        """Test ConnectWidgetResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConnectWidgetResponseBody`
        """
        model = ConnectWidgetResponseBody()  # noqa: E501
        if include_optional:
            return ConnectWidgetResponseBody(
                user = mx_platform_python.models.connect_widget_response.ConnectWidgetResponse(
                    connect_widget_url = 'https://int-widgets.moneydesktop.com/md/connect/jb1rA14m85tw2lyvpgfx4gc6d3Z8z8Ayb8', 
                    guid = 'USR-fa7537f3-48aa-a683-a02a-b18940482f54', )
            )
        else:
            return ConnectWidgetResponseBody(
        )
        """

    def testConnectWidgetResponseBody(self):
        """Test ConnectWidgetResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
