# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.widget_request import WidgetRequest  # noqa: E501

class TestWidgetRequest(unittest.TestCase):
    """WidgetRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WidgetRequest:
        """Test WidgetRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WidgetRequest`
        """
        model = WidgetRequest()  # noqa: E501
        if include_optional:
            return WidgetRequest(
                client_redirect_url = 'https://{yoursite.com}',
                color_scheme = 'light',
                connections_use_case_filter = False,
                current_institution_code = 'mxbank',
                current_institution_guid = 'INS-f1a3285d-e855-b61f-6aa7-8ae575c0e0e9',
                current_member_guid = 'MBR-7c6f361b-e582-15b6-60c0-358f12466b4b',
                disable_background_agg = False,
                disable_institution_search = False,
                enable_app2app = False,
                include_identity = False,
                include_transactions = True,
                insight_guid = '',
                iso_country_code = ["US","CA"],
                is_mobile_webview = False,
                microwidget_instance_id = '',
                mode = 'aggregation',
                oauth_referral_source = 'BROWSER',
                ui_message_version = 4,
                ui_message_webview_url_scheme = '',
                update_credentials = False,
                use_cases = ["PFM"],
                widget_type = 'connect_widget'
            )
        else:
            return WidgetRequest(
                widget_type = 'connect_widget',
        )
        """

    def testWidgetRequest(self):
        """Test WidgetRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
