# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.microdeposit_response import MicrodepositResponse  # noqa: E501

class TestMicrodepositResponse(unittest.TestCase):
    """MicrodepositResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MicrodepositResponse:
        """Test MicrodepositResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MicrodepositResponse`
        """
        model = MicrodepositResponse()  # noqa: E501
        if include_optional:
            return MicrodepositResponse(
                error_message = '',
                guid = 'MIC-09ba578e-8448-4f7f-89e1-b62ff2517edb',
                institution_code = 'mxbank',
                institution_name = 'MX Bank',
                status = 'INITIATED',
                updated_at = '2023-06-01T19:18:06Z',
                verified_at = ''
            )
        else:
            return MicrodepositResponse(
        )
        """

    def testMicrodepositResponse(self):
        """Test MicrodepositResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
