# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.user_response_body import UserResponseBody  # noqa: E501

class TestUserResponseBody(unittest.TestCase):
    """UserResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserResponseBody:
        """Test UserResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserResponseBody`
        """
        model = UserResponseBody()  # noqa: E501
        if include_optional:
            return UserResponseBody(
                user = mx_platform_python.models.user_response.UserResponse(
                    email = 'email@provider.com', 
                    guid = 'USR-d74cb14f-fd0a-449f-991b-e0362a63d9c6', 
                    id = 'My-Unique-ID', 
                    is_disabled = False, 
                    metadata = '{\"first_name\": \"Steven\", \"last_name\": \"Universe\"}', )
            )
        else:
            return UserResponseBody(
        )
        """

    def testUserResponseBody(self):
        """Test UserResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
