# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.managed_account_update_request_body import ManagedAccountUpdateRequestBody  # noqa: E501

class TestManagedAccountUpdateRequestBody(unittest.TestCase):
    """ManagedAccountUpdateRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManagedAccountUpdateRequestBody:
        """Test ManagedAccountUpdateRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManagedAccountUpdateRequestBody`
        """
        model = ManagedAccountUpdateRequestBody()  # noqa: E501
        if include_optional:
            return ManagedAccountUpdateRequestBody(
                account = mx_platform_python.models.managed_account_update_request.ManagedAccountUpdateRequest(
                    account_number = '5366', 
                    apr = 1.0, 
                    apy = 1.0, 
                    available_balance = 1000.0, 
                    available_credit = 1000.0, 
                    balance = 1000.0, 
                    cash_surrender_value = 1000.0, 
                    credit_limit = 100.0, 
                    currency_code = 'USD', 
                    day_payment_is_due = 20, 
                    death_benefit = 1000, 
                    id = '1040434698', 
                    interest_rate = 1.0, 
                    is_closed = False, 
                    is_hidden = False, 
                    last_payment = 100.0, 
                    last_payment_at = '2015-10-13T17:57:37.000Z', 
                    loan_amount = 1000.0, 
                    matures_on = '2015-10-13T17:57:37.000Z', 
                    metadata = 'some metadata', 
                    minimum_balance = 100.0, 
                    minimum_payment = 10.0, 
                    name = 'Test account 2', 
                    nickname = 'Swiss Account', 
                    original_balance = 10.0, 
                    payment_due_at = '2015-10-13T17:57:37.000Z', 
                    payoff_balance = 10.0, 
                    routing_number = '68899990000000', 
                    started_on = '2015-10-13T17:57:37.000Z', 
                    subtype = 'NONE', 
                    type = 'SAVINGS', )
            )
        else:
            return ManagedAccountUpdateRequestBody(
        )
        """

    def testManagedAccountUpdateRequestBody(self):
        """Test ManagedAccountUpdateRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
