# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.tagging_response_body import TaggingResponseBody  # noqa: E501

class TestTaggingResponseBody(unittest.TestCase):
    """TaggingResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaggingResponseBody:
        """Test TaggingResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaggingResponseBody`
        """
        model = TaggingResponseBody()  # noqa: E501
        if include_optional:
            return TaggingResponseBody(
                tagging = mx_platform_python.models.tagging_response.TaggingResponse(
                    guid = 'TGN-007f5486-17e1-45fc-8b87-8f03984430fe', 
                    member_is_managed_by_user = False, 
                    tag_guid = 'TAG-40faf068-abb4-405c-8f6a-e883ed541fff', 
                    transaction_guid = 'TRN-810828b0-5210-4878-9bd3-f4ce514f90c4', 
                    user_guid = 'USR-11141024-90b3-1bce-cac9-c06ced52ab4c', )
            )
        else:
            return TaggingResponseBody(
        )
        """

    def testTaggingResponseBody(self):
        """Test TaggingResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
