# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mx_platform_python.api.microdeposits_api import MicrodepositsApi  # noqa: E501


class TestMicrodepositsApi(unittest.TestCase):
    """MicrodepositsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MicrodepositsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_microdeposit(self) -> None:
        """Test case for create_microdeposit

        Create or pre-initiate a microdeposit  # noqa: E501
        """
        pass

    def test_delete_microdeposit(self) -> None:
        """Test case for delete_microdeposit

        Delete a microdeposit  # noqa: E501
        """
        pass

    def test_list_user_microdeposits(self) -> None:
        """Test case for list_user_microdeposits

        List all microdeposits for a user  # noqa: E501
        """
        pass

    def test_list_user_verifications(self) -> None:
        """Test case for list_user_verifications

        List all verifications for a user  # noqa: E501
        """
        pass

    def test_read_user_microdeposit(self) -> None:
        """Test case for read_user_microdeposit

        Read a microdeposit for a user  # noqa: E501
        """
        pass

    def test_verify_microdeposit(self) -> None:
        """Test case for verify_microdeposit

        Verify a Microdeposit  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
