"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mx_platform_python
from mx_platform_python.model.pagination_response import PaginationResponse
from mx_platform_python.model.spending_plan_iteration_response import SpendingPlanIterationResponse
globals()['PaginationResponse'] = PaginationResponse
globals()['SpendingPlanIterationResponse'] = SpendingPlanIterationResponse
from mx_platform_python.model.spending_plan_iterations_response import SpendingPlanIterationsResponse


class TestSpendingPlanIterationsResponse(unittest.TestCase):
    """SpendingPlanIterationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpendingPlanIterationsResponse(self):
        """Test SpendingPlanIterationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpendingPlanIterationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
