# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mx_platform_python.models.account_numbers_response_body import AccountNumbersResponseBody  # noqa: E501

class TestAccountNumbersResponseBody(unittest.TestCase):
    """AccountNumbersResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountNumbersResponseBody:
        """Test AccountNumbersResponseBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountNumbersResponseBody`
        """
        model = AccountNumbersResponseBody()  # noqa: E501
        if include_optional:
            return AccountNumbersResponseBody(
                account_numbers = [
                    mx_platform_python.models.account_number_response.AccountNumberResponse(
                        account_guid = 'ACT-06d7f45b-caae-0f6e-1384-01f52e75dcb1', 
                        account_number = '10001', 
                        guid = 'ACN-8899832e-e5b4-42cd-aa25-bbf1dc889a8f', 
                        loan_guarantor = 'U.S. DEPARTMENT OF EDUCATION', 
                        loan_reference_number = '123456789012345', 
                        institution_number = '123', 
                        member_guid = 'MBR-7c6f361b-e582-15b6-60c0-358f12466b4b', 
                        passed_validation = True, 
                        routing_number = '68899990000000', 
                        sequence_number = '1-01', 
                        transit_number = '12345', 
                        user_guid = 'USR-fa7537f3-48aa-a683-a02a-b18940482f54', )
                    ],
                pagination = mx_platform_python.models.pagination_response.PaginationResponse(
                    current_page = 1, 
                    per_page = 25, 
                    total_entries = 1, 
                    total_pages = 1, )
            )
        else:
            return AccountNumbersResponseBody(
        )
        """

    def testAccountNumbersResponseBody(self):
        """Test AccountNumbersResponseBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
