# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mx_platform_python.api.taggings_api import TaggingsApi  # noqa: E501


class TestTaggingsApi(unittest.TestCase):
    """TaggingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaggingsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_tagging(self) -> None:
        """Test case for create_tagging

        Create tagging  # noqa: E501
        """
        pass

    def test_delete_tagging(self) -> None:
        """Test case for delete_tagging

        Delete tagging  # noqa: E501
        """
        pass

    def test_list_taggings(self) -> None:
        """Test case for list_taggings

        List taggings  # noqa: E501
        """
        pass

    def test_read_tagging(self) -> None:
        """Test case for read_tagging

        Read tagging  # noqa: E501
        """
        pass

    def test_update_tagging(self) -> None:
        """Test case for update_tagging

        Update tagging  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
