# coding: utf-8

"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  Just getting started? See our [use case guides](/use-cases/). 

    The version of the OpenAPI document: 20111101
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mx_platform_python.api.ach_return_api import AchReturnApi  # noqa: E501


class TestAchReturnApi(unittest.TestCase):
    """AchReturnApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AchReturnApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_create_ach_return(self) -> None:
        """Test case for create_ach_return

        Create ACH Return  # noqa: E501
        """
        pass

    def test_list_ach_retruns(self) -> None:
        """Test case for list_ach_retruns

        List ACH Returns  # noqa: E501
        """
        pass

    def test_read_ach_retrun(self) -> None:
        """Test case for read_ach_retrun

        Read ACH Return  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
