"""
    MX Platform API

    The MX Platform API is a powerful, fully-featured API designed to make aggregating and enhancing financial data easy and reliable. It can seamlessly connect your app or website to tens of thousands of financial institutions.  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import mx_platform_python
from mx_platform_python.model.partner_authorization_code_response import PartnerAuthorizationCodeResponse
globals()['PartnerAuthorizationCodeResponse'] = PartnerAuthorizationCodeResponse
from mx_platform_python.model.partner_authorization_code_response_body import PartnerAuthorizationCodeResponseBody


class TestPartnerAuthorizationCodeResponseBody(unittest.TestCase):
    """PartnerAuthorizationCodeResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartnerAuthorizationCodeResponseBody(self):
        """Test PartnerAuthorizationCodeResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PartnerAuthorizationCodeResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
